### ISSUE TITLE
Práctica interfaz

### ISSUE THREAD

**Issue by bg55-a** [SistemasTecTlaxiaco/practicaprototipos-prototipoxd#2]
[interfaz grafica adobe.pdf](https://github.com/SistemasTecTlaxiaco/practicaprototipos-prototipoxd/files/8182350/interfaz.grafica.adobe.pdf)

**Comment by josealfredo79** [comment]
@bg55-a Falta la calificación aqui por favor

**Comment by josealfredo79** [comment]
Nuevamente indico que la calificación debe ir aqui

**Comment by josealfredo79** [comment]
La calificacion nuevamente indico hace falta

**Comment by josealfredo79** [comment]
Ruego, suplico...ya no soy docente, soy rogón, aquí debe ir la calificacion

**Comment by EvelynLopezz** [comment]
Calificación 19

**Comment by josealfredo79** [comment]
Bien hecho y revisado
