### ISSUE TITLE
Práctica con Visual Studio con eventos (Calculadora)

### ISSUE THREAD

**Issue by Anthony4523** [SistemasTecTlaxiaco/practicaprototipos-prototipoxd#3]
[Práctica con Visual Studio con eventos.pdf](https://github.com/SistemasTecTlaxiaco/practicaprototipos-prototipoxd/files/6160945/Practica.con.Visual.Studio.con.eventos.pdf)

**Comment by CxrlosMX** [comment]
Calificó equipo Cheack:
Calificación obtenida: 100/100

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado.
